# Use new container infrastructure to enable caching
sudo: false

# Do not choose a language; we provide our own build tools.
language: generic

# Caching so the next build will be fast too.
cache:
  directories:
  - $HOME/.stack

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

branches:
  only:
    - hakyll

before_install:
  # Download and unpack the stack executable
  - mkdir -p ~/.local/bin
  - export PATH=$HOME/.local/bin:$PATH
  - travis_retry curl -L https://get.haskellstack.org/stable/linux-x86_64.tar.gz | tar xz --wildcards --strip-components=1 -C ~/.local/bin '*/stack'

install:
  # Build dependencies
  - stack install --no-terminal --install-ghc -j2

before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..

script:
  # Build the blog instead of running tests
  - stack exec blog build

after_success:
  - git config --global user.email "mauriciofierrom@gmail.com"
  - git config --global user.name "Mauricio Fierro"
  - cd _site/ && git status
  - git remote show origin
  - git add --all
  - git commit -m "Snapshot (`TZ=America/Guayaquil date '+%F %T %Z'`) [skip ci]"
  - git push "https://$GH_TOKEN@github.com/mauriciofierrom/mauriciofierrom.github.io.git" master > /dev/null 2>&1
