sudo: false

language: nix
nix: 2.0.4

# Caching so the next build will be fast too.
cache:
  directories:
  - /nix

# Ensure necessary system libraries are present
addons:
  apt:
    packages:
      - libgmp-dev

branches:
  only:
    - hakyll

before_script:
  - cd _site
  - git checkout master
  - git pull origin master
  - cd ..

script:
  # Build the blog instead of running tests
  - nix-build release.nix
  - LANG=en_US.UTF-8 ./result/bin/blog build

after_success:
  - git config --global user.email "mauriciofierrom@gmail.com"
  - git config --global user.name "Mauricio Fierro"
  - cd _site/ && git status
  - git remote show origin
  - git add --all
  - git commit -m "Snapshot (`TZ=America/Guayaquil date '+%F %T %Z'`) [skip ci]"
  - git push "https://$GH_TOKEN@github.com/mauriciofierrom/mauriciofierrom.github.io.git" master > /dev/null 2>&1
